backend/controllers/BlogController.php
<?php 
	namespace backend\controllers;

	use Yii;
	use yii\web\Controller;
	use yii\web\UploadedFile;
    use common\components\ValidUsers;

	use yii\filters\VerbFilter;
    use yii\helpers\ArrayHelper;
	use yii\web\NotFoundHttpException;
	use yii\web\Response;

    // use common\models\Menu;
    use common\models\Model;
    use common\models\Posts;

    
	use yii\data\ActiveDataProvider;

	// $_SESSION['KCFINDER']['disabled'] = false;
	// $_SESSION['KCFINDER']['uploadURL'] = $url."/images/blog/";
	// $_SESSION['KCFINDER']['uploadDir'] = Yii::getAlias('@proyect')."/images/blog/";
	class BlogController extends Controller
	{
		private $_ValidUser;

		public function actionIndex(){
			$this->_ValidUser = new ValidUsers;
			$this->_ValidUser->AccesControl([1]);
			// 1 = Users Admin
			// 2 = Users moderador
			$data = Yii::$app->session->get('UserData');
			$this->layout = $data['LayoutUser'];
			$data['ModelPosts']  = $modelPosts = Posts::find();

			$data['dataProvider']  = new ActiveDataProvider([
				    'query' => $modelPosts,
				    'pagination' => [
				        'pageSize' => 20,
				    ],
				]);
			

			// $data['searchModel'] = $searchModel = new Menu();
			// $data['dataProvider'] = $dataProvider = Menu::find()->all();

			return $this->render('index',$data);
		}

		public function actionDelete($id){
			$this->_ValidUser = new ValidUsers;
			$this->_ValidUser->AccesControl([1]);
			// 1 = Users Admin
			// 2 = Users moderador
			// $data = Yii::$app->session->get('UserData');

			$this->layout = false;
			$modelPosts = Posts::findOne($id);
			$transaction = \Yii::$app->db->beginTransaction();
			try {
				if($modelPosts->delete()){
					$transaction->commit();
					Yii::$app->session->setFlash('success', "Post delete correctly.");
					$this->redirect(['/blog']);
				}else{
					Yii::$app->session->setFlash('error', "There was an error Deleting Post.");
					$transaction->rollBack();
					$this->redirect(['/blog']);

				}
			} catch (Exception $e) {

				Yii::$app->session->setFlash('error', "There was an error deleting the post.");
				$transaction->rollBack();
				$this->redirect(['/blog']);
			}
			
			
		}


		public function actionCreatepost(){
			$this->_ValidUser = new ValidUsers;
			$this->_ValidUser->AccesControl([1]);
			// 1 = Users Admin
			// 2 = Users moderador
			$data = Yii::$app->session->get('UserData');
			$this->layout = $data['LayoutUser'];
			
			/////////////////Importante para el funcionamiento de///////////////////////
			/////////////////kcfinder y CKeditor carga de archivos//////////////////////
			$protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off' || $_SERVER['SERVER_PORT'] == 443) ? "https://" : "http://";
			$url=$protocol.$_SERVER['HTTP_HOST'].Yii::getAlias('@proyect');
				 $configkcfinder = fopen(Yii::getAlias('@webroot').'/settingkcfinder.txt', 'w');
				 $uploadURL = $url."/images/blog/";
				 $uploadDir = Yii::getAlias('@webroot')."/../images/blog/";
				 $datafile = json_encode(array('uploadURL' =>  $uploadURL,'uploadDir' => $uploadDir));
				 fwrite($configkcfinder,$datafile);
				 fclose($configkcfinder);
			 ///////////////////////////////////////////////////////////////////////////////


			$ModelPost = new Posts;

			if($ModelPost->load(Yii::$app->request->post())){
				if($ModelPost->validate()){
					$upload = true;
					$ModelPost->PhotoBlog = UploadedFile::getInstance($ModelPost, 'PhotoBlog');
					if($ModelPost->PhotoBlog != null)
							$upload = $ModelPost->upload();

						if($upload){
							if($ModelPost->save()){
								Yii::$app->session->setFlash('success', "Blog Post Insert correctly");
								return $this->redirect(['/blog']);
							}else{
								$data['ModelPost'] = $ModelPost;
							 	Yii::$app->session->setFlash('error', "There was an error creating blog post.");

							}
						}else{
							$data['ModelPost'] = $ModelPost;
							Yii::$app->session->setFlash('error', "Fail to upload Image.");
						}
				}else{

					Yii::$app->session->setFlash('error', "There was an error creating blog post check the data.");
				}
			
		   	}
			    $data['ModelPost'] = $ModelPost;

			// ajax validation
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ArrayHelper::merge(
                    Posts::validate($ModelPost)
                );
            }


			return $this->render('posts',$data);
		}




		public function actionUpdate($id){
			$this->_ValidUser = new ValidUsers;
			$this->_ValidUser->AccesControl([1]);
			// 1 = Users Admin
			// 2 = Users moderador
			$data = Yii::$app->session->get('UserData');
			$this->layout = $data['LayoutUser'];

			/////////////////Importante para el funcionamiento de///////////////////////
			/////////////////kcfinder y CKeditor carga de archivos//////////////////////
			$protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off' || $_SERVER['SERVER_PORT'] == 443) ? "https://" : "http://";
			$url=$protocol.$_SERVER['HTTP_HOST'].Yii::getAlias('@proyect');
				 $configkcfinder = fopen(Yii::getAlias('@webroot').'/settingkcfinder.txt', 'w');
				 $uploadURL = $url."/images/blog/";
				 $uploadDir = Yii::getAlias('@webroot')."/../images/blog/";
				 $datafile = json_encode(array('uploadURL' =>  $uploadURL,'uploadDir' => $uploadDir));
				 fwrite($configkcfinder,$datafile);
				 fclose($configkcfinder);
			 ///////////////////////////////////////////////////////////////////////////////


			$ModelPost = Posts::findOne($id);
			if($ModelPost->load(Yii::$app->request->post())){
				//$ModelPost->Content = Yii::$app->request->post()['Posts']['Content'];
				if($ModelPost->validate()){
					$upload = true;
					$ModelPost->PhotoBlog = UploadedFile::getInstance($ModelPost, 'PhotoBlog');
					if($ModelPost->PhotoBlog != null)
							$upload = $ModelPost->upload();

						if($upload){
							if($ModelPost->save()){
								Yii::$app->session->setFlash('success', "Blog Post Insert correctly");
								return $this->redirect(['/blog']);
							}else{
								$data['ModelPost'] = $ModelPost;
							 	Yii::$app->session->setFlash('error', "There was an error creating blog post.");

							}
						}else{
							$data['ModelPost'] = $ModelPost;
							Yii::$app->session->setFlash('error', "Fail to upload Image.");
						}

				}else{
					Yii::$app->session->setFlash('error', "There was an error creating blog post check the data.");
				}
			
		   	}

			    $data['ModelPost'] = $ModelPost;
			// ajax validation
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ArrayHelper::merge(
                    Posts::validate($ModelPost)
                );
            }


			return $this->render('posts',$data);
		}



	}

frontend/controllers/BlogController.php
<?php 
	namespace frontend\controllers;

	use Yii;
	use yii\web\Controller;
	use yii\web\UploadedFile;
    use common\components\ValidUsers;

	use yii\filters\VerbFilter;
    use yii\helpers\ArrayHelper;
	use yii\web\NotFoundHttpException;
	use yii\web\Response;

    // use common\models\Menu;
    use common\models\Model;
    use common\models\Posts;

    
	use yii\data\ActiveDataProvider;

	// $_SESSION['KCFINDER']['disabled'] = false;
	// $_SESSION['KCFINDER']['uploadURL'] = $url."/images/blog/";
	// $_SESSION['KCFINDER']['uploadDir'] = Yii::getAlias('@proyect')."/images/blog/";
	class BlogController extends Controller
	{
		private $_ValidUser;

		public function actionIndex(){
			$UserData =  Yii::$app->AccessControl->Verify([1,2]);
			// 1 = Users Admin
			// 2 = Users moderador
			$data = [];
			$this->layout = $UserData->getLayout();

			$data['ModelPosts']  = $modelPosts = Posts::find();

			$data['dataProvider']  = new ActiveDataProvider([
				    'query' => $modelPosts,
				    'pagination' => [
				        'pageSize' => 20,
				    ],
				]);
			

			// $data['searchModel'] = $searchModel = new Menu();
			// $data['dataProvider'] = $dataProvider = Menu::find()->all();

			return $this->render('index',$data);
		}

		public function actionDelete($id){
			$UserData =  Yii::$app->AccessControl->Verify([1,2]);
			// 1 = Users Admin
			// 2 = Users moderador
			// $data = Yii::$app->session->get('UserData');

			$this->layout = false;
			$modelPosts = Posts::findOne($id);
			$transaction = \Yii::$app->db->beginTransaction();
			try {
				if($modelPosts->delete()){
					$transaction->commit();
					Yii::$app->session->setFlash('success', "Post delete correctly.");
					$this->redirect(['/blog']);
				}else{
					Yii::$app->session->setFlash('error', "There was an error Deleting Post.");
					$transaction->rollBack();
					$this->redirect(['/blog']);

				}
			} catch (Exception $e) {

				Yii::$app->session->setFlash('error', "There was an error deleting the post.");
				$transaction->rollBack();
				$this->redirect(['/blog']);
			}
			
			
		}


		public function actionCreatepost(){
			$UserData =  Yii::$app->AccessControl->Verify([1,2]);
			// 1 = Users Admin
			// 2 = Users moderador
			$data = [];
			$this->layout = $UserData->getLayout();
			
			/////////////////Importante para el funcionamiento de///////////////////////
			/////////////////kcfinder y CKeditor carga de archivos//////////////////////
			$protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off' || $_SERVER['SERVER_PORT'] == 443) ? "https://" : "http://";
			$url=$protocol.$_SERVER['HTTP_HOST'].Yii::getAlias('@proyect');
				 $configkcfinder = fopen(Yii::getAlias('@webroot').'/settingkcfinder.txt', 'w');
				 $uploadURL = $url."/images/blog/";
				 $uploadDir = Yii::getAlias('@webroot')."/../images/blog/";
				 $datafile = json_encode(array('uploadURL' =>  $uploadURL,'uploadDir' => $uploadDir));
				 fwrite($configkcfinder,$datafile);
				 fclose($configkcfinder);
			 ///////////////////////////////////////////////////////////////////////////////


			$ModelPost = new Posts;

			if($ModelPost->load(Yii::$app->request->post())){
				if($ModelPost->validate()){
					$upload = true;
					$ModelPost->PhotoBlog = UploadedFile::getInstance($ModelPost, 'PhotoBlog');
					if($ModelPost->PhotoBlog != null)
							$upload = $ModelPost->upload();

						if($upload){
							if($ModelPost->save()){
								Yii::$app->session->setFlash('success', "Blog Post Insert correctly");
								return $this->redirect(['/blog']);
							}else{
								$data['ModelPost'] = $ModelPost;
							 	Yii::$app->session->setFlash('error', "There was an error creating blog post.");

							}
						}else{
							$data['ModelPost'] = $ModelPost;
							Yii::$app->session->setFlash('error', "Fail to upload Image.");
						}
				}else{

					Yii::$app->session->setFlash('error', "There was an error creating blog post check the data.");
				}
			
		   	}
			    $data['ModelPost'] = $ModelPost;

			// ajax validation
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ArrayHelper::merge(
                    Posts::validate($ModelPost)
                );
            }


			return $this->render('posts',$data);
		}




		public function actionUpdate($id){
			$UserData =  Yii::$app->AccessControl->Verify([1,2]);
			// 1 = Users Admin
			// 2 = Users moderador
			$data = [];
			$this->layout = $UserData->getLayout();

			/////////////////Importante para el funcionamiento de///////////////////////
			/////////////////kcfinder y CKeditor carga de archivos//////////////////////
			$protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off' || $_SERVER['SERVER_PORT'] == 443) ? "https://" : "http://";
			$url=$protocol.$_SERVER['HTTP_HOST'].Yii::getAlias('@proyect');
				 $configkcfinder = fopen(Yii::getAlias('@webroot').'/settingkcfinder.txt', 'w');
				 $uploadURL = $url."/images/blog/";
				 $uploadDir = Yii::getAlias('@webroot')."/../images/blog/";
				 $datafile = json_encode(array('uploadURL' =>  $uploadURL,'uploadDir' => $uploadDir));
				 fwrite($configkcfinder,$datafile);
				 fclose($configkcfinder);
			 ///////////////////////////////////////////////////////////////////////////////


			$ModelPost = Posts::findOne($id);
			if($ModelPost->load(Yii::$app->request->post())){
				//$ModelPost->Content = Yii::$app->request->post()['Posts']['Content'];
				if($ModelPost->validate()){
					$upload = true;
					$ModelPost->PhotoBlog = UploadedFile::getInstance($ModelPost, 'PhotoBlog');
					if($ModelPost->PhotoBlog != null)
							$upload = $ModelPost->upload();

						if($upload){
							if($ModelPost->save()){
								Yii::$app->session->setFlash('success', "Blog Post Insert correctly");
								return $this->redirect(['/blog']);
							}else{
								$data['ModelPost'] = $ModelPost;
							 	Yii::$app->session->setFlash('error', "There was an error creating blog post.");

							}
						}else{
							$data['ModelPost'] = $ModelPost;
							Yii::$app->session->setFlash('error', "Fail to upload Image.");
						}

				}else{
					Yii::$app->session->setFlash('error', "There was an error creating blog post check the data.");
				}
			
		   	}

			    $data['ModelPost'] = $ModelPost;
			// ajax validation
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ArrayHelper::merge(
                    Posts::validate($ModelPost)
                );
            }


			return $this->render('posts',$data);
		}



	}

backend/views/blog/index.php
<?php 
use yii\helpers\Html;
use backend\assets\AppAssetLayoutAll;
    AppAssetLayoutAll::register($this);
    use common\components\datatables\DataTables;
    $this->title = 'Blog';
 ?>

<div class="container-fluid">

    <h1>Posts Blog Xtreme</h1>
    <hr>
<?= Html::a('<i class="fa fa-plus"></i> Create New Post', ['/blog/createpost'], ['class'=>'btn btn-success']) ?>
<br><br><br>
<div class="row-fluid">
<?php 

echo DataTables::widget([
    'dataProvider' => $dataProvider,
    'columns' => [

        ['class' => 'yii\grid\SerialColumn'],
        // Simple columns defined by the data contained in $dataProvider.
        // Data from the model's column will be used.
    
        [
            'attribute' => 'Tittle',
            'format' => 'text',
            'contentOptions'=>['style'=>'vertical-align:middle;'],
        ],
        [
          'attribute' => 'Image',
           'class' => 'yii\grid\DataColumn', // can be omitted, as it is the default
            'value' => function ($data) {
              $htm = "<img src='".Yii::getAlias("@proyect")."/images/blog/".$data->ImageUrl."' style='margin: auto; width: auto; height: 30px;''></img>";
                return $htm; // $data['name'] for array data, e.g. using SqlDataProvider.
            },
            'format' => 'html',
            'contentOptions'=>['style'=>'text-align: center; vertical-align:middle;'],
        ],
        [
            'attribute' => 'Publication Date',
            'value' => function ($data) {
              $htm = "<b><i>".$data->PubDate."</i></b>";
                return $htm; // $data['name'] for array data, e.g. using SqlDataProvider.
            },
            'format' => 'html',
            'contentOptions'=>['style'=>'vertical-align:middle;'],
        ],
        [
            'class' => 'yii\grid\ActionColumn',
            'template' => '<div class="btn-group" > {update} {delete} </div>',
            'buttons' => [
                'delete' => function($url, $model){
                    return Html::a('<span class="fa fa-trash"></span>', ['delete', 'id' => $model->PostID], [
                        'class' => 'btn btn-danger click-confirm',
                        'tittle-alert' => 'Delete Information',
                        'text-alert'  => 'Are You Sure? When you delete the Post ['.$model->Tittle.'], you will not be able to retrieve it later',
                    ]);
                },
                'update' => function($url, $model){
                    return Html::a('<span class="fa fa-edit"></span>', ['update', 'id' => $model->PostID,], [
                        'class' => 'btn btn-info',

                        
                    ]);
                }
               
            ],
            'contentOptions'=>['style'=>'min-width: 100px; text-align: center; vertical-align:middle;'],
        ],
        
    ],
    'clientOptions' => [
    "lengthMenu"=> [[10,20,-1], [10,20,Yii::t('app',"All")]],
    "info"=>false,
    "retrieve" => true,
    "responsive"=>'true', 
    "dom"=> 'lfTrtip',
    "tableTools"=>[
        "aButtons"=> [  
            // [
            // "sExtends"=> "copy",
            // "sButtonText"=> Yii::t('app',"Copy to clipboard")
            // ],
            // [
            // "sExtends"=> "csv",
            // "sButtonText"=> Yii::t('app',"Save to CSV")
            // ],
            // [
            // "sExtends"=> "xls",
            // "oSelectorOpts"=> ["page"=> 'current'],
            // ],[
            // "sExtends"=> "pdf",
            // "sButtonText"=> Yii::t('app',"Save to PDF")
            // ],[
            // "sExtends"=> "print",
            // "sButtonText"=> Yii::t('app',"Print")
            // ],
        ]
    ]
],
]);
 ?>
</div>
</div>
<?php 
if (Yii::$app->session->hasFlash('success')):
		$this->registerJS('
			$(document).ready(function(){
				_Message("success","Success!","'.Yii::$app->session->getFlash('success').'");
			});

			');
	endif;

	if (Yii::$app->session->hasFlash('error')):

		$this->registerJS('
			$(document).ready(function(){
				_Message("error","Error!","'.Yii::$app->session->getFlash('error').'");
			});

			');
	endif;
 ?>

backend/views/blog/posts.php
<?php 
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use backend\assets\AppAssetLayoutAll;
    AppAssetLayoutAll::register($this);
use backend\assets\AppAsset;
    AppAsset::register($this);
    $this->title = 'New Post Blog';
 ?>
<div class="container-fluid">
    
    <h1><?=($ModelPost->isNewRecord)? 'Create Post' : 'Update Post'; ?> </h1>
     <div class="row-fluid">

            <div class="customer-form">

                <?php $form = ActiveForm::begin(['id' => 'dynamic-form-Post']); ?>
                <div class="row">
                    <div class="col-sm-12">
                        <?= $form->field($ModelPost, 'Tittle')->textInput(['maxlength' => true,'id'=>'tittleid','required'=>true]); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <?= $form->field($ModelPost, 'PhotoBlog')->fileInput(['class'=>'imgpostchang']); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <?= $form->field($ModelPost, 'Content')->textarea(['maxlength' => true,'style'=>'height:150;','id'=>'res-editor']); ?>
                    </div>
                </div>

                <div class="form-group">
                    <?= Html::submitButton($ModelPost->isNewRecord ? 'Create' : 'Update', ['class' => 'btn btn-primary click-confirm', 'style'=>'width:100%;',
                            "tittle-alert" => $ModelPost->isNewRecord ? 'Create Post' : 'Update Post',
                            "text-alert" => $ModelPost->isNewRecord ? 'It´s a point to create a new post Do you want to continue?' : 'It´s a point to Update the Post ['.$ModelPost->Tittle.'] Do you want to continue?',

                    ]) ?>
                </div>

                <?php ActiveForm::end(); ?>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <?php $imgrute = ($ModelPost->ImageUrl)?  $ModelPost->ImageUrl : 'default.png'; ?>
                     <img id="wrapper" src="<?= Yii::getAlias('@proyect').'/images/blog/'.$imgrute ?>" class="img-responsive" style="margin: auto; width: auto; height: 200px;">
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="row-fluid">
                        <h1 id="prevTitle"><?= $ModelPost->Tittle; ?></h1>
                    </div>
                    <div class="row-fluid">
                        <span id="prevText">
                             <?= $ModelPost->Content; ?>
                        </span>
                    </div>
                </div>
            </div>
    </div>
</div>

 <?php 
if (Yii::$app->session->hasFlash('success')):
        $this->registerJS('
            $(document).ready(function(){
                _Message("success","Success!","'.Yii::$app->session->getFlash('success').'");
            });

            ');
    endif;

    if (Yii::$app->session->hasFlash('error')):

        $this->registerJS('
            $(document).ready(function(){
                _Message("error","Error!","'.Yii::$app->session->getFlash('error').'");
            });

            ');
    endif;
    $JS = "
        function readURL(input) {

            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#wrapper').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }
        CKEDITOR.replace('res-editor');
        $(document).ready(function(){

            $('.imgpostchang').change(function(){
                readURL(this);
            });

            $('#tittleid').on('keyup',function(){
                    $('#prevTitle').html(this.value);
            });

            CKEDITOR.instances['res-editor'].on('instanceReady',function(){
                this.document.on('keyup', function(){
                     $('#prevText').html(CKEDITOR.instances['res-editor'].getData());
                });
            });
        });

    ";
    $this->registerJS($JS);
 ?>