backend/controllers/TipsandstyleController.php
<?php 
	namespace backend\controllers;

	use Yii;
	use yii\web\Controller;
	use yii\web\UploadedFile;
    use common\components\ValidUsers;

	use yii\filters\VerbFilter;
    use yii\helpers\ArrayHelper;
	use yii\web\NotFoundHttpException;
	use yii\web\Response;

    use common\models\Model;
    use common\models\TargetsTips;
    use common\models\Tips;
   

    
	use yii\data\ActiveDataProvider;


	class TipsandstyleController extends Controller
	{
		private $_ValidUser;

		public function actionIndex(){
			$this->_ValidUser = new ValidUsers;
			$this->_ValidUser->AccesControl([1]);
			// 1 = Users Admin
			// 2 = Users moderador
			$data = Yii::$app->session->get('UserData');
			$this->layout = $data['LayoutUser'];
			$data['ModelTargetTips']  = $ModelTargetTips = TargetsTips::find();

			$data['dataProvider']  = new ActiveDataProvider([
				    'query' => $ModelTargetTips,
				    'pagination' => [
				        'pageSize' => 20,
				    ],
				]);
			

			// $data['searchModel'] = $searchModel = new Menu();
			// $data['dataProvider'] = $dataProvider = Menu::find()->all();

			return $this->render('index',$data);
		}

		public function actionDelete($id){
			$this->_ValidUser = new ValidUsers;
			$this->_ValidUser->AccesControl([1]);
			// 1 = Users Admin
			// 2 = Users moderador
			// $data = Yii::$app->session->get('UserData');

			$this->layout = false;
			$modelTarget = TargetsTips::findOne($id);
			$transaction = \Yii::$app->db->beginTransaction();
			try {
				if($modelTarget->delete()){
					$transaction->commit();
					Yii::$app->session->setFlash('success', "Menu delete correctly.");
					$this->redirect(['/tipsandstyle']);
				}else{
					Yii::$app->session->setFlash('error', "There was an error creating the menu.");
					$transaction->rollBack();
					$this->redirect(['/tipsandstyle']);

				}
			} catch (Exception $e) {

				Yii::$app->session->setFlash('error', "There was an error creating the menu.");
				$transaction->rollBack();
				$this->redirect(['/tipsandstyle']);
			}
			
			
		}


		public function actionCreate(){
			$this->_ValidUser = new ValidUsers;
			$this->_ValidUser->AccesControl([1]);
			// 1 = Users Admin
			// 2 = Users moderador
			$data = Yii::$app->session->get('UserData');
			$this->layout = $data['LayoutUser'];


			$TargetsModel = new TargetsTips;
			$TipsModel = [new Tips];
			//$items = ArrayHelper::map(Role::find()->all(), 'RoleID', 'RoleName');

			if($TargetsModel->load(Yii::$app->request->post())){
				//Targets y Tips

				$upload = true;
				$TargetsModel->PhotoTarget = UploadedFile::getInstance($TargetsModel, 'PhotoTarget');
				if($TargetsModel->PhotoTarget != null)
						$upload = $TargetsModel->upload();


				$TipsModel = Model::createMultiple(Tips::classname());
        		Model::loadMultiple($TipsModel, Yii::$app->request->post());
	            $valid = $TargetsModel->validate();
	            $valid = Model::validateMultiple($TipsModel) && $valid;

		            if ($valid) {
		                $transaction = \Yii::$app->db->beginTransaction();

		                try {
		                	if(!$upload){
								Yii::$app->session->setFlash('error', "Fail to upload Image.");
		                        $transaction->rollBack();
		                        $data['TargetsModel'] = $TargetsModel;
			    				$data['TipsModel'] = $TipsModel;
			    				return $this->render('formtips',$data);
							}
		                    if ($flag = $TargetsModel->save(false)){
		                        foreach ($TipsModel as $modelTip) {
		                            $modelTip->TargetsTipsID = $TargetsModel->TargetsTipsID;
		                            if (! ($flag = $modelTip->save(false))){
		                            	Yii::$app->session->setFlash('error', "There was an error creating the menu.");
		                                $transaction->rollBack();
		                                break;
		                            }
		                        }
		                    }

		                    if ($flag){
		                        $transaction->commit();
		                        Yii::$app->session->setFlash('success', "Target and tips created correctly");
		                         return $this->redirect(['/tipsandstyle']);
		                    }
		                } catch (Exception $e) {
		                	Yii::$app->session->setFlash('error', "There was an error creating the Target and tips.");
		                    $transaction->rollBack();
		                }
		            }else{
		            	Yii::$app->session->setFlash('error', "There is an incorrect data verification, please try again");
		            	$data['TargetsModel'] = $TargetsModel;
				    	$data['TipsModel'] = $TipsModel;

		            }
		   	}else{

			    $data['TargetsModel'] = $TargetsModel;
			    $data['TipsModel'] = $TipsModel;

			}
			// ajax validation
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ArrayHelper::merge(
                    Model::validateMultiple($TipsModel),
                    Model::validate($TargetsModel)
                );
            }


			return $this->render('formtips',$data);
		}




		public function actionUpdate($id){
			$this->_ValidUser = new ValidUsers;
			$this->_ValidUser->AccesControl([1]);
			// 1 = Users Admin
			// 2 = Users moderador
			$data = Yii::$app->session->get('UserData');
			$this->layout = $data['LayoutUser'];


			$TargetsModel = TargetsTips::findOne($id);
			$TipsModel = (!empty($TargetsModel->tips))? $TargetsModel->tips : [new Tips] ;

			if($TargetsModel->load(Yii::$app->request->post())){

				$upload = true;
				$TargetsModel->PhotoTarget = UploadedFile::getInstance($TargetsModel, 'PhotoTarget');
				if($TargetsModel->PhotoTarget != null)
						$upload = $TargetsModel->upload();

				//Menu y Subs Menus
				$oldIDs = ArrayHelper::map($TipsModel, 'TipsID', 'TipsID');
				$TipsModel = Model::createMultiple(Tips::classname());
        		Model::loadMultiple($TipsModel, Yii::$app->request->post());
        		$deletedIDs = array_diff($oldIDs, array_filter(ArrayHelper::map($TipsModel, 'TipsID', 'TipsID')));
	            $valid = $TargetsModel->validate();
	            $valid = Model::validateMultiple($TipsModel) && $valid;

		            if ($valid) {
		                $transaction = \Yii::$app->db->beginTransaction();

		                try {
		                	if(!$upload){
								Yii::$app->session->setFlash('error', "Fail to upload Image.");
		                        $transaction->rollBack();
		                        $data['TargetsModel'] = $TargetsModel;
			    				$data['TipsModel'] = $TipsModel;
			    				return $this->render('formtips',$data);
							}
		                    if ($flag = $TargetsModel->save(false)){
		                    		if (! empty($deletedIDs)) {
				                            Tips::deleteAll(['TipsID' => $deletedIDs]);
				                        }
		                        foreach ($TipsModel as $modelTips) {
		                            $modelTips->TargetsTipsID = $TargetsModel->TargetsTipsID;
		                            if (! ($flag = $modelTips->save(false))){
		                            	Yii::$app->session->setFlash('error', "There was an error updating the menu.");
		                                $transaction->rollBack();
		                                break;
		                            }
		                        }
		                    }

		                    if ($flag){
		                        $transaction->commit();
		                        Yii::$app->session->setFlash('success', "Target an tips update correctly");
		                         return $this->redirect(['/tipsandstyle']);
		                    }
		                } catch (Exception $e) {
		                	Yii::$app->session->setFlash('error', "There was an error updating target and tips.");
		                    $transaction->rollBack();
		                }
		            }else{
		            	Yii::$app->session->setFlash('error', "There is an incorrect data verification, please try again");
		            	$data['TargetsModel'] = $TargetsModel;
				    	$data['TipsModel'] = $TipsModel;

		            }
			
		   	}else{

			    $data['TargetsModel'] = $TargetsModel;
			    $data['TipsModel'] = $TipsModel;

			}
			// ajax validation
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ArrayHelper::merge(
                    Model::validateMultiple($TipsModel),
                    Model::validate($TargetsModel)
                );
            }


			return $this->render('formtips',$data);
		}



	}

frontend/controllers/TipsandstyleController.php
<?php 
	namespace frontend\controllers;

	use Yii;
	use yii\web\Controller;
	use yii\web\UploadedFile;
    use common\components\ValidUsers;

	use yii\filters\VerbFilter;
    use yii\helpers\ArrayHelper;
	use yii\web\NotFoundHttpException;
	use yii\web\Response;

    use common\models\Model;
    use common\models\TargetsTips;
    use common\models\Tips;
   

    
	use yii\data\ActiveDataProvider;


	class TipsandstyleController extends Controller
	{
		private $_ValidUser;

		public function actionIndex(){
			$UserData =  Yii::$app->AccessControl->Verify([1,2]);
			// 1 = Users Admin
			// 2 = Users moderador
			$data = [];
			$this->layout = $UserData->getLayout();
			$data['ModelTargetTips']  = $ModelTargetTips = TargetsTips::find();

			$data['dataProvider']  = new ActiveDataProvider([
				    'query' => $ModelTargetTips,
				    'pagination' => [
				        'pageSize' => 20,
				    ],
				]);
			

			// $data['searchModel'] = $searchModel = new Menu();
			// $data['dataProvider'] = $dataProvider = Menu::find()->all();

			return $this->render('index',$data);
		}

		public function actionDelete($id){
			$UserData =  Yii::$app->AccessControl->Verify([1,2]);
			// 1 = Users Admin
			// 2 = Users moderador
			// $data = Yii::$app->session->get('UserData');

			$this->layout = false;
			$modelTarget = TargetsTips::findOne($id);
			$transaction = \Yii::$app->db->beginTransaction();
			try {
				if($modelTarget->delete()){
					$transaction->commit();
					Yii::$app->session->setFlash('success', "Menu delete correctly.");
					$this->redirect(['/tipsandstyle']);
				}else{
					Yii::$app->session->setFlash('error', "There was an error creating the menu.");
					$transaction->rollBack();
					$this->redirect(['/tipsandstyle']);

				}
			} catch (Exception $e) {

				Yii::$app->session->setFlash('error', "There was an error creating the menu.");
				$transaction->rollBack();
				$this->redirect(['/tipsandstyle']);
			}
			
			
		}


		public function actionCreate(){
			$UserData =  Yii::$app->AccessControl->Verify([1,2]);
			// 1 = Users Admin
			// 2 = Users moderador
			$data = [];
			$this->layout = $UserData->getLayout();


			$TargetsModel = new TargetsTips;
			$TipsModel = [new Tips];
			//$items = ArrayHelper::map(Role::find()->all(), 'RoleID', 'RoleName');

			if($TargetsModel->load(Yii::$app->request->post())){
				//Targets y Tips

				$upload = true;
				$TargetsModel->PhotoTarget = UploadedFile::getInstance($TargetsModel, 'PhotoTarget');
				if($TargetsModel->PhotoTarget != null)
						$upload = $TargetsModel->upload();


				$TipsModel = Model::createMultiple(Tips::classname());
        		Model::loadMultiple($TipsModel, Yii::$app->request->post());
	            $valid = $TargetsModel->validate();
	            $valid = Model::validateMultiple($TipsModel) && $valid;

		            if ($valid) {
		                $transaction = \Yii::$app->db->beginTransaction();

		                try {
		                	if(!$upload){
								Yii::$app->session->setFlash('error', "Fail to upload Image.");
		                        $transaction->rollBack();
		                        $data['TargetsModel'] = $TargetsModel;
			    				$data['TipsModel'] = $TipsModel;
			    				return $this->render('formtips',$data);
							}
		                    if ($flag = $TargetsModel->save(false)){
		                        foreach ($TipsModel as $modelTip) {
		                            $modelTip->TargetsTipsID = $TargetsModel->TargetsTipsID;
		                            if (! ($flag = $modelTip->save(false))){
		                            	Yii::$app->session->setFlash('error', "There was an error creating the menu.");
		                                $transaction->rollBack();
		                                break;
		                            }
		                        }
		                    }

		                    if ($flag){
		                        $transaction->commit();
		                        Yii::$app->session->setFlash('success', "Target and tips created correctly");
		                         return $this->redirect(['/tipsandstyle']);
		                    }
		                } catch (Exception $e) {
		                	Yii::$app->session->setFlash('error', "There was an error creating the Target and tips.");
		                    $transaction->rollBack();
		                }
		            }else{
		            	Yii::$app->session->setFlash('error', "There is an incorrect data verification, please try again");
		            	$data['TargetsModel'] = $TargetsModel;
				    	$data['TipsModel'] = $TipsModel;

		            }
		   	}else{

			    $data['TargetsModel'] = $TargetsModel;
			    $data['TipsModel'] = $TipsModel;

			}
			// ajax validation
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ArrayHelper::merge(
                    Model::validateMultiple($TipsModel),
                    Model::validate($TargetsModel)
                );
            }


			return $this->render('formtips',$data);
		}




		public function actionUpdate($id){
			$UserData =  Yii::$app->AccessControl->Verify([1,2]);
			// 1 = Users Admin
			// 2 = Users moderador
			$data = [];
			$this->layout = $UserData->getLayout();


			$TargetsModel = TargetsTips::findOne($id);
			$TipsModel = (!empty($TargetsModel->tips))? $TargetsModel->tips : [new Tips] ;

			if($TargetsModel->load(Yii::$app->request->post())){

				$upload = true;
				$TargetsModel->PhotoTarget = UploadedFile::getInstance($TargetsModel, 'PhotoTarget');
				if($TargetsModel->PhotoTarget != null)
						$upload = $TargetsModel->upload();

				//Menu y Subs Menus
				$oldIDs = ArrayHelper::map($TipsModel, 'TipsID', 'TipsID');
				$TipsModel = Model::createMultiple(Tips::classname());
        		Model::loadMultiple($TipsModel, Yii::$app->request->post());
        		$deletedIDs = array_diff($oldIDs, array_filter(ArrayHelper::map($TipsModel, 'TipsID', 'TipsID')));
	            $valid = $TargetsModel->validate();
	            $valid = Model::validateMultiple($TipsModel) && $valid;

		            if ($valid) {
		                $transaction = \Yii::$app->db->beginTransaction();

		                try {
		                	if(!$upload){
								Yii::$app->session->setFlash('error', "Fail to upload Image.");
		                        $transaction->rollBack();
		                        $data['TargetsModel'] = $TargetsModel;
			    				$data['TipsModel'] = $TipsModel;
			    				return $this->render('formtips',$data);
							}
		                    if ($flag = $TargetsModel->save(false)){
		                    		if (! empty($deletedIDs)) {
				                            Tips::deleteAll(['TipsID' => $deletedIDs]);
				                        }
		                        foreach ($TipsModel as $modelTips) {
		                            $modelTips->TargetsTipsID = $TargetsModel->TargetsTipsID;
		                            if (! ($flag = $modelTips->save(false))){
		                            	Yii::$app->session->setFlash('error', "There was an error updating the menu.");
		                                $transaction->rollBack();
		                                break;
		                            }
		                        }
		                    }

		                    if ($flag){
		                        $transaction->commit();
		                        Yii::$app->session->setFlash('success', "Target an tips update correctly");
		                         return $this->redirect(['/tipsandstyle']);
		                    }
		                } catch (Exception $e) {
		                	Yii::$app->session->setFlash('error', "There was an error updating target and tips.");
		                    $transaction->rollBack();
		                }
		            }else{
		            	Yii::$app->session->setFlash('error', "There is an incorrect data verification, please try again");
		            	$data['TargetsModel'] = $TargetsModel;
				    	$data['TipsModel'] = $TipsModel;

		            }
			
		   	}else{

			    $data['TargetsModel'] = $TargetsModel;
			    $data['TipsModel'] = $TipsModel;

			}
			// ajax validation
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ArrayHelper::merge(
                    Model::validateMultiple($TipsModel),
                    Model::validate($TargetsModel)
                );
            }


			return $this->render('formtips',$data);
		}



	}

backend/views/tipsandstyle/formtips.php
<?php 
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\components\DinamycForm\DynamicFormWidget;
use backend\assets\AppAssetLayoutAll;
use common\components\kartik\colorinput\ColorInput;
    AppAssetLayoutAll::register($this);
    $this->title = 'Tips And Style';
 ?>
<div class="container-fluid">
    
    <h1><?=($TargetsModel->isNewRecord)? 'Create Target and Tips' : 'Update Target and Tips'; ?> </h1>
     <div class="row-fluid">

            <div class="customer-form">

                <?php $form = ActiveForm::begin(['id' => 'dynamic-form-menu']); ?>
                <div class="row">
                    <div class="col-sm-6">
                        <?= $form->field($TargetsModel, 'Tittle')->textInput(['maxlength' => true,'id'=>'tittlechangeprev']) ?>
                    </div>
                    <div class="col-sm-6">
                         <?= $form->field($TargetsModel, 'PhotoTarget')->fileInput(['class'=>'imgpostchang']); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <?php $colorVlue = ($TargetsModel->Color)? $TargetsModel->Color : 'rgb(106, 168, 79)'; ?>
                        <?= $form->field($TargetsModel, 'Color')->widget(ColorInput::classname(),
                            [

                                'options' => ['placeholder' => 'Select color ...','value'=>$colorVlue, 'readonly'=>true, 'class'=>'colorchange'],
                                'pluginOptions' => ['showInput' => false,'preferredFormat' => 'rgb']
                             ]) ?>
                    </div>
                    <div class="col-sm-6">
                        <?php $imgrute = ($TargetsModel->ImageUrl)?  $TargetsModel->ImageUrl : 'default.png';
                                $tittletext = ($TargetsModel->Tittle)? $TargetsModel->Tittle : 'Tittle';
                         ?>
                        <div class="row">
                            <div class="col-sm-12" id="prevtarg" style="color:white; background-color: <?= $colorVlue; ?>;">
                                <img id="wrapper" align="left" src="<?= Yii::getAlias('@proyect').'/images/TargetTips/'.$imgrute ?>" class="img-responsive" style="width: auto; height: 70px; margin-left: -20px; margin-right: 15px;">
                                <b id="tittleprev" ><?= $tittletext; ?></b><br>
                                1. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.
                            </div>
                        </div>
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading"><h4><i class="fa fa-cogs"></i> Configure Menu</h4></div>
                    <div class="panel-body">


                        <div class="NosingleMenu" style="">
                         <?php DynamicFormWidget::begin([
                            'widgetContainer' => 'dynamicform_wrapper', // required: only alphanumeric characters plus "_" [A-Za-z0-9_]
                            'widgetBody' => '.container-items', // required: css class selector
                            'widgetItem' => '.item', // required: css class
                            'limit' => 10, // the maximum times, an element can be cloned (default 999)
                            'min' => 1, // 0 or 1 (default 1)
                            'insertButton' => '.add-item', // css class
                            'deleteButton' => '.remove-item', // css class
                            'model' => $TipsModel[0],
                            'formId' => 'dynamic-form-menu',
                            'formFields' => [
                                'Content',
                            ],
                        ]); ?>

                        <div class="container-items"><!-- widgetContainer -->
                        <?php foreach ($TipsModel as $i => $modelTips): ?>
                            <div class="item panel panel-default"><!-- widgetBody -->
                                <div class="panel-heading">
                                    <h3 class="panel-title pull-left">Tip</h3>
                                    <div class="pull-right">
                                        <button type="button" class="add-item btn btn-success btn-xs"><i class="glyphicon glyphicon-plus"></i></button>
                                        <button type="button" class="remove-item btn btn-danger btn-xs"><i class="glyphicon glyphicon-minus"></i></button>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="panel-body">
                                    <?php
                                        // necessary for update action.
                                        if (!$modelTips->isNewRecord) {
                                            echo Html::activeHiddenInput($modelTips, "[{$i}]TipsID");
                                        }
                                    ?>
                                    <?= $form->field($modelTips, "[{$i}]Content")->textarea(['maxlength' => true,'class'=>'form-control val-vaciar']) ?>
                                    <!-- .row -->
                                    <!-- .row -->
                                </div>
                            </div>
                        <?php endforeach; ?>
                        </div>
                        <?php DynamicFormWidget::end(); ?>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <?= Html::submitButton($TargetsModel->isNewRecord ? 'Create' : 'Update', ['class' => 'btn btn-primary click-confirm', 'style'=>'width:100%;',
                            "tittle-alert" => $TargetsModel->isNewRecord ? 'Create Target and Tips' : 'Update target an Tips',
                            "text-alert" => $TargetsModel->isNewRecord ? 'It´s a point to create a new target and tip Do you want to continue?' : 'It´s a point to Update the target ['.$TargetsModel->Tittle.'] Do you want to continue?',

                    ]) ?>
                </div>

                <?php ActiveForm::end(); ?>

            </div>
    </div>
</div>


 <?php 
$JS = "
        function readURL(input) {

            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#wrapper').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }
        $(document).ready(function(){

            $('.imgpostchang').change(function(){
                readURL(this);
            });
            $('.colorchange').change(function(){
                $('#prevtarg').css('background-color',this.value);
            });
            $('#tittlechangeprev').on('keyup',function(){
                $('#tittleprev').html(this.value);
            });
            
        });

        ";
 $this->registerJS($JS);

if (Yii::$app->session->hasFlash('success')):
        $this->registerJS('
            $(document).ready(function(){
                _Message("success","Success!","'.Yii::$app->session->getFlash('success').'");
            });

            ');
    endif;

    if (Yii::$app->session->hasFlash('error')):

        $this->registerJS('
            $(document).ready(function(){
                _Message("error","Error!","'.Yii::$app->session->getFlash('error').'");
            });

            ');
    endif;
 ?>

backend/views/tipsandstyle/index.php
<?php 
use yii\helpers\Html;
use backend\assets\AppAssetLayoutAll;
    AppAssetLayoutAll::register($this);
    use common\components\datatables\DataTables;
    $this->title = 'Tips And Style';
 ?>

<div class="container-fluid">

    <h1>Tips And Style</h1>
    <hr>
<?= Html::a('<i class="fa fa-plus"></i> Create New Target tips', ['/tipsandstyle/create'], ['class'=>'btn btn-success']) ?>
<br><br><br>
<div class="row-fluid">
<?php 

echo DataTables::widget([
    'dataProvider' => $dataProvider,
    'columns' => [

        ['class' => 'yii\grid\SerialColumn'],
        // Simple columns defined by the data contained in $dataProvider.
        // Data from the model's column will be used.
    
        [
            'attribute' => 'Tittle',
            'format' => 'text',
            'contentOptions'=>['style'=>'vertical-align:middle;'],
        ],
        [
          'attribute' => 'Preview target',
           'class' => 'yii\grid\DataColumn', // can be omitted, as it is the default
            'value' => function ($data) {
              $htm = '<div class="row" style=" width: 80%; margin:0 auto;" >
                            <div class="col-sm-12" id="prevtarg" style="color:white; background-color: '.$data->Color.';">
                                <img id="wrapper" align="left" src="'.Yii::getAlias('@proyect').'/images/TargetTips/'.$data->ImageUrl.'" class="img-responsive" style="width: auto; height: 70px; margin-left: -20px; margin-right: 15px;">
                                <b id="tittleprev" >'.$data->Tittle.'</b><br>
                                1. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.
                            </div>
                        </div>';
                return $htm; // $data['name'] for array data, e.g. using SqlDataProvider.
            },
            'format' => 'html',
            'contentOptions'=>['style'=>'text-align: center; vertical-align:middle;'],
        ],
        [
          'attribute' => 'Amount Tips',
           'class' => 'yii\grid\DataColumn', // can be omitted, as it is the default
            'value' => function ($data) {
              
                return count($data->tips); // $data['name'] for array data, e.g. using SqlDataProvider.
            },
            'format' => 'text',
            'contentOptions'=>['style'=>'vertical-align:middle;'],
        ],

        [
            'class' => 'yii\grid\ActionColumn',
            'template' => '<div class="btn-group" > {update} {delete} </div>',
            'buttons' => [
                'delete' => function($url, $model){
                    return Html::a('<span class="fa fa-trash"></span>', ['delete', 'id' => $model->TargetsTipsID], [
                        'class' => 'btn btn-danger click-confirm',
                        'tittle-alert' => 'Delete Information',
                        'text-alert'  => 'Are You Sure? When you delete the menu ['.$model->Tittle.'], you will not be able to retrieve it later',
                    ]);
                },
                'update' => function($url, $model){
                    return Html::a('<span class="fa fa-edit"></span>', ['update', 'id' => $model->TargetsTipsID,], [
                        'class' => 'btn btn-info',

                        
                    ]);
                }
               
            ],
            'contentOptions'=>['style'=>'min-width: 100px; text-align: center; vertical-align:middle;'],
        ],
        
    ],
    'clientOptions' => [
    "lengthMenu"=> [[10,20,-1], [10,20,Yii::t('app',"All")]],
    "info"=>false,
    "retrieve" => true,
    "responsive"=>'true', 
    "dom"=> 'lfTrtip',
    "tableTools"=>[
        "aButtons"=> [  
            // [
            // "sExtends"=> "copy",
            // "sButtonText"=> Yii::t('app',"Copy to clipboard")
            // ],
            // [
            // "sExtends"=> "csv",
            // "sButtonText"=> Yii::t('app',"Save to CSV")
            // ],
            // [
            // "sExtends"=> "xls",
            // "oSelectorOpts"=> ["page"=> 'current'],
            // ],[
            // "sExtends"=> "pdf",
            // "sButtonText"=> Yii::t('app',"Save to PDF")
            // ],[
            // "sExtends"=> "print",
            // "sButtonText"=> Yii::t('app',"Print")
            // ],
        ]
    ]
],
]);
 ?>
</div>
</div>
<?php 
if (Yii::$app->session->hasFlash('success')):
		$this->registerJS('
			$(document).ready(function(){
				_Message("success","Success!","'.Yii::$app->session->getFlash('success').'");
			});

			');
	endif;

	if (Yii::$app->session->hasFlash('error')):

		$this->registerJS('
			$(document).ready(function(){
				_Message("error","Error!","'.Yii::$app->session->getFlash('error').'");
			});

			');
	endif;
 ?>