backend/controllers/UsuarioController.php
<?php 
	namespace backend\controllers;
	use Yii;
	use yii\web\Controller;
	use yii\filters\VerbFilter;
	use yii\filters\AccessControl;

	use common\models\Account;
	use common\models\Agency;
	use common\models\UserAccount;
    use common\models\Country;
    use common\models\ValidarUser;
    use common\models\Role;
	use common\models\UserByRole;

	use common\components\ValidUsers;
	use yii\helpers\ArrayHelper;

	use yii\data\ActiveDataProvider;
	use yii\db\Expression;
	

	class UsuarioController extends Controller
	{
		private $_valiUser;
        
        //funcion que llama la vista principal de usuarios
        public function actionIndex()
        {
        	$data = Yii::$app->session->get('UserData');
        	$this->_valiUser = new ValidUsers;
            $this->_valiUser->AccesControl([1]);
			$this->layout = $data['LayoutUser'];

            $pAgency = Agency::find();//trae todo de agency de la bd
            $pUserAccount = UserAccount::find()->asArray()->all();//trae Useraccount de l bd	
            $Country = Country::find()->asArray()->all();

            $data['AgencysDat']  = new ActiveDataProvider([
				    'query' => $pAgency,
				    'pagination' => [
				        'pageSize' => 20,
				    ],
				]);   


            $data['Countrys'] = $Country;
            $data['Agencys'] = $pAgency;
            $data['UserAccounts'] = $pUserAccount;
            $data['model'] = new ValidarUser();

            return $this->render('index', $data);
        }

        public function actionDelete($id){
			$this->_valiUser = new ValidUsers;
			$this->_valiUser->AccesControl([1]);
			// 1 = Users Admin
			// 2 = Users moderador
			// $data = Yii::$app->session->get('UserData');

			$this->layout = false;
			$ModelAccount = Account::findOne($id);
			$transaction = \Yii::$app->db->beginTransaction();
			try {
				if($ModelAccount->delete()){
					$transaction->commit();
					Yii::$app->session->setFlash('success', "Menu delete correctly.");
					$this->redirect(['/usuario']);
				}else{
					Yii::$app->session->setFlash('error', "There was an error creating the menu.");
					$transaction->rollBack();
					$this->redirect(['/menu']);

				}
			} catch (Exception $e) {

				Yii::$app->session->setFlash('error', "There was an error creating the menu.");
				$transaction->rollBack();
				$this->redirect(['/usuario']);
			}
			
			
		}

////Controlador para Crear usuarios
        public function actionCreateuser()
        {
        	$data = Yii::$app->session->get('UserData');
        	$this->_valiUser = new ValidUsers;
            $this->_valiUser->AccesControl([1]);
			$this->layout = $data['LayoutUser'];
			
			$data['ModelAccount'] = $ModelAccount = new Account;
			$data['ModelUserAccount'] = $ModelUserAccount = new UserAccount;
			$data['ModelAgency'] = $ModelAgency = new Agency;
			$data['ModelByRole'] = $ModelByRole = new UserByRole;

			$data['ItemsRole'] = ArrayHelper::map(Role::find()->all(), 'RoleID', 'RoleName');
			$data['ItemsCountry'] = ArrayHelper::map(Country::find()->all(), 'CountryID', 'Name');

			$transaction = \Yii::$app->db->beginTransaction();
			if(Yii::$app->request->post()){
				$ModelUserAccount->load(Yii::$app->request->post());
				$ModelAgency->load(Yii::$app->request->post());
				$ModelByRole->load(Yii::$app->request->post());
				$valid = $ModelUserAccount->validate();
				$valid = $ModelAgency->validate() && $valid;
				$valid = $ModelByRole->validate() && $valid;

				if($valid){
					try {
						$ModelAccount->IsActive = 1;
						$ModelAccount->AuditDate = new Expression('NOW()');
						$ModelAccount->AuditUser = "System";

						if(!$ModelAccount->save()){
							Yii::$app->session->setFlash('error', "There was an error creating the user.");
					        $transaction->rollBack();

					        echo "create Account";
					        exit();
						}

						$ModelUserAccount->AccountID = $ModelAccount->AccountID;
						$ModelUserAccount->UserPassword = md5($ModelUserAccount->UserPassword);
						if(!$ModelUserAccount->save()){
							Yii::$app->session->setFlash('error', "There was an error creating the user.");
					        $transaction->rollBack();
					        echo "create UserAccount";
					        exit();
						}


						$ModelAgency->AccountID = $ModelAccount->AccountID;

						if(!$ModelAgency->save()){
							Yii::$app->session->setFlash('error', "There was an error creating the user.");
					        $transaction->rollBack();
					        echo "create Agency";
					        exit();
						}

						$ModelByRole->UserName = $ModelUserAccount->UserName;
						// var_dump($ModelByRole->RoleID);exit();
						if(!$ModelByRole->save()){
							Yii::$app->session->setFlash('error', "There was an error creating the user.");
					        $transaction->rollBack();
					        echo "UserByRole";
					        exit();
						}

						Yii::$app->session->setFlash('success', "Menu created correctly");
						$transaction->commit();
						return $this->redirect(['/usuario']);

					} catch (Exception $e) {
						Yii::$app->session->setFlash('error', "There was an error creating the user.");
					        $transaction->rollBack();
					        $data['ModelAccount'] = $ModelAccount;
							$data['ModelUserAccount'] = $ModelUserAccount;
							$data['ModelAgency'] = $ModelAgency;
							$data['ModelByRole'] = $ModelByRole;
						
					}
				}else{
					Yii::$app->session->setFlash('error', "There was an error in validation data. Cheked an try again");
					$data['ModelAccount'] = $ModelAccount = new Account;
					$data['ModelUserAccount'] = $ModelUserAccount = new UserAccount;
					$data['ModelAgency'] = $ModelAgency = new Agency;
					$data['ModelByRole'] = $ModelByRole = new UserByRole;
				}
			}



            return $this->render('userform', $data);
        }


//Controlador para Actualizar datos de usuario
        public function actionUpdate($id)
        {
        	$data = Yii::$app->session->get('UserData');
        	$this->_valiUser = new ValidUsers;
            $this->_valiUser->AccesControl([1]);
			$this->layout = $data['LayoutUser'];
			
			$ModelFindUserAccount = UserAccount::findOne(['AccountID' => $id]);

			$ModelAccount = Account::findOne($id);
			$ModelAccount->isNewRecord = false;
			$data['ModelAccount'] = $ModelAccount;
			$data['ModelUserAccount'] = $ModelUserAccount = $ModelAccount->userAccount;
			$data['ModelAgency'] = $ModelAgency = $ModelAccount->agency;
			$data['ModelByRole'] = $ModelByRole = $ModelAccount->userAccount->userByRole;
			// $roles = [];
			// array_push($roles,$ModelAccount->userAccount->userByRole->RoleID);

			// $data['ItemsRoleUse'] = $roles;
			$data['ItemsRole'] = ArrayHelper::map(Role::find()->all(), 'RoleID', 'RoleName');
			$data['ItemsCountry'] = ArrayHelper::map(Country::find()->all(), 'CountryID', 'Name');

			$transaction = \Yii::$app->db->beginTransaction();
			if(Yii::$app->request->post()){
				$ModelUserAccount->load(Yii::$app->request->post());
				$ModelAgency->load(Yii::$app->request->post());
				$ModelByRole->load(Yii::$app->request->post());
				$valid = $ModelUserAccount->validate();
				$valid = $ModelAgency->validate() && $valid;
				$valid = $ModelByRole->validate() && $valid;

				if($valid){
					try {
						$ModelAccount->IsActive = 1;
						$ModelAccount->AuditDate = new Expression('NOW()');
						$ModelAccount->AuditUser = "System";

						if(!$ModelAccount->save()){
							Yii::$app->session->setFlash('error', "There was an error updating the user.");
					        $transaction->rollBack();

					        echo "create Account";
					        exit();
						}

						$ModelUserAccount->AccountID = $ModelAccount->AccountID;
						if($ModelUserAccount->UserPassword != $ModelFindUserAccount->UserPassword && !empty($ModelUserAccount->UserPassword )){
							$ModelUserAccount->UserPassword = md5($ModelUserAccount->UserPassword);
						}else{ $ModelUserAccount->UserPassword = $ModelFindUserAccount->UserPassword; }
						if(!$ModelUserAccount->save()){
							Yii::$app->session->setFlash('error', "There was an error updating the user.");
					        $transaction->rollBack();
					        echo "create UserAccount";
					        exit();
						}


						$ModelAgency->AccountID = $ModelAccount->AccountID;

						if(!$ModelAgency->save()){
							Yii::$app->session->setFlash('error', "There was an error updating the user.");
					        $transaction->rollBack();
					        echo "create Agency";
					        exit();
						}

						$ModelByRole->UserName = $ModelUserAccount->UserName;
						// var_dump($ModelByRole->RoleID);exit();
						if(!$ModelByRole->save()){
							Yii::$app->session->setFlash('error', "There was an error updating the user.");
					        $transaction->rollBack();
					        echo "UserByRole";
					        exit();
						}

						Yii::$app->session->setFlash('success', "user update correctly");
						$transaction->commit();
						return $this->redirect(['/usuario']);

					} catch (Exception $e) {
						Yii::$app->session->setFlash('error', "There was an error updating the user.");
					        $transaction->rollBack();
					        $data['ModelAccount'] = $ModelAccount;
							$data['ModelUserAccount'] = $ModelUserAccount;
							$data['ModelAgency'] = $ModelAgency;
							$data['ModelByRole'] = $ModelByRole;
						
					}
				}else{
					Yii::$app->session->setFlash('error', "There was an error in validation data. Cheked an try again");
					$data['ModelAccount'] = $ModelAccount = new Account;
					$data['ModelUserAccount'] = $ModelUserAccount = new UserAccount;
					$data['ModelAgency'] = $ModelAgency = new Agency;
					$data['ModelByRole'] = $ModelByRole = new UserByRole;
				}
			}



            return $this->render('userform', $data);
        }

////Controlador para la vista del role
        public function actionRoles() {
        	$data = Yii::$app->session->get('UserData');
        	$this->_valiUser = new ValidUsers;
            $this->_valiUser->AccesControl([1]);
			$this->layout = $data['LayoutUser'];

frontend/views/usuario/index.php
<?php
 
use frontend\assets\AppAssetLayoutAll;
AppAssetLayoutAll::register($this);
 
use frontend\assets\AppAsset;
AppAsset::register($this);
 
use yii\helpers\Html;
use yii\bootstrap\Button;
use yii\bootstrap\ActiveForm;
use common\components\datatables\DataTables;
$this->title = 'Usuarios';
$this->params['breadcrumbs'][] = $this->title;
?>
 
 
<div class="usuario">
    <h2 style="color: var(--color-principal);"><?= Html::encode($this->title)?></h2>
    <hr>
    <?= Html::a('<i class="fa fa-plus"></i> Añadir nuevo usuario', ['/usuario/createuser'], ['class'=>'btn btn-color-especial']) ?>
    <!--   <button type="button" class="btn btn-success" data-toggle="modal" data-target="#usermodal"><i class="fa fa-plus"></i></button> -->
    <!-- Fin Formulario Modificar Modal -->
    <br><br>
    <div class="container-fluid">
      
    <?php 
//var_dump($AgencysDat);die();
        echo DataTables::widget([
            'dataProvider' => $AgencysDat,

            'columns' => [
                ['class' => 'yii\grid\SerialColumn',],

                [
                  'attribute' => 'Nombre de Usuario',
                   'class' => 'yii\grid\DataColumn', // can be omitted, as it is the default
                    'value' => function ($data) {
                        return $data->account->userAccount->UserName; // $data['name'] for array data, e.g. using SqlDataProvider.
                    },
                    'format' => 'text',
                    'contentOptions'=>['style'=>' vertical-align:middle;'],
                ],
                [
                    'attribute' => 'FirstName',
                    'format' => 'text',
                    'contentOptions'=>['style'=>'vertical-align:middle; min-width: 30%;'],
                ],
                [
                    'attribute' => 'LastName',
                    'format' => 'text',
                    'contentOptions'=>['style'=>'vertical-align:middle;'],
                ],
                [
                  'attribute' => 'Tipo de Usuario',
                   'class' => 'yii\grid\DataColumn', // can be omitted, as it is the default
                    'value' => function ($data) {
                        return $data->account->userAccount->typeUsers->Name; // $data['name'] for array data, e.g. using SqlDataProvider.
                    },
                    'format' => 'text',
                    'contentOptions'=>['style'=>'text-align: center; vertical-align:middle;'],
                ],
                [
                    'class' => 'yii\grid\ActionColumn',
                    'template' => '<div class="btn-group" > {update} {delete} </div>',
                    'buttons' => [
                        'delete' => function($url, $model){
                            return Html::a('<span class="fa fa-trash"></span>', ["delete","id" => $model->AccountID], [
                                'id'=>$model->AccountID,
                                'class' => 'btn btn-danger click-confirm',
                                'tittle-alert'  => 'Eliminar información',
                                'text-alert'  => '¿Estás seguro? Cuando elimines el usuario ['.$model->account->userAccount->UserName.'],no podrás recuperarlo más tarde.',
                            ]);
                        },
                        'update' => function($url, $model){
                            return Html::a('<span class="fa fa-edit"></span>',[ "update","id"=>$model->AccountID], [
                                'id'=>$model->AccountID,
                                'class' => 'btn btn-color-especial',   
                            ]);
                        }
                       
                    ],

                    'contentOptions'=>['style'=>'min-width: 100px; text-align: center; vertical-align:middle;'],
                ],
            ],

            'clientOptions' => [
                "lengthMenu"=> [[10,20,-1], [10,20,Yii::t('app',"All")]],
                "info"=>false,
                "retrieve" => true,
                "responsive"=>'true', 
                "dom"=> 'lfTrtip',
                "tableTools"=>[
                    "aButtons"=> [  
                        
                    ]
                ],
                'language'=>[
                    'processing'    => Yii::t('app', 'Procesando...'),
                    'search'        => Yii::t('app', 'Buscar:'),
                    'lengthMenu'    => Yii::t('app','Mostrar _MENU_ Entradas'),
                    'info'        => Yii::t('app','Mostrando del _START_ al _END_ de _TOTAL_ entradas'),
                    'infoEmpty'  => Yii::t('app','Mostrando del 0 al 0 de 0 entradas'),
                    'infoFiltered'  => Yii::t('app','(Filtrado de _MAX_ entradas totales)'),
                    'infoPostFix'   => '',
                    'loadingRecords'=> Yii::t('app','Cargando...'),
                    'zeroRecords'   => Yii::t('app','No se encontraron registros coincidentes'),
                    'emptyTable'    => Yii::t('app','No hay datos disponibles en la tabla'),
                    'paginate' => [
                        'first'  => Yii::t('app','Primero'),
                        'previous'  => Yii::t('app','Anterior'),
                        'next'    => Yii::t('app','Siguiente'),
                        'last'    => Yii::t('app','Último'),
                    ],
                    'aria' => [
                        'sortAscending' => Yii::t('app',': activate to sort column ascending'),
                        'sortDescending'=> Yii::t('app',': activate to sort column descending'),
                    ]
                ],
            ],
        ]);
    ?>
</div> 

<?php 
    if (Yii::$app->session->hasFlash('success')):
        $this->registerJS('
            $(document).ready(function(){
                _Message("success","¡Exito!","'.Yii::$app->session->getFlash('success').'");
            });

        ');
    endif;

    if (Yii::$app->session->hasFlash('error')):

        $this->registerJS('
            $(document).ready(function(){
                _Message("error","¡Error!","'.Yii::$app->session->getFlash('error').'");
            });

        ');
    endif;
?>

frontend/views/usuario/roles.php
<?php
 
use frontend\assets\AppAssetLayoutAll;
AppAssetLayoutAll::register($this);
 
use frontend\assets\AppAsset;
use yii\helpers\Html;
use yii\bootstrap\Button;
use yii\bootstrap\ActiveForm;
use common\components\datatables\DataTables;
$this->title = 'Roles';
$this->params['breadcrumbs'][] = $this->title;
?>
 
 
<div class="HomeRole">
    <h2 style="color: var(--color-principal);"><?= Html::encode($this->title)?></h2>
    <div>
        <button type="button" class="btn btn-color-especial" data-toggle="modal" data-target="#modal-create"><i class="fa fa-plus"></i> Añadir rol</button>
    </div>
    <br> 
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="row">
                <?php   
                    echo DataTables::widget([
                            'dataProvider' => $dataProvider,
                            'columns' => [
                                ['class' => 'yii\grid\SerialColumn'],
                                // Simple columns defined by the data contained in $dataProvider.
                                // Data from the model's column will be used.
                                [
                                  'attribute' => 'Nombre del Rol',
                                   'class' => 'yii\grid\DataColumn', // can be omitted, as it is the default
                                    'value' => function ($data) {
                                        return $data->RoleName; // $data['name'] for array data, e.g. using SqlDataProvider.
                                    },
                                    'format' => 'text',
                                    'contentOptions'=>['style'=>'text-align: center; vertical-align:middle;'],
                                ],

                                [
                                    'class' => 'yii\grid\ActionColumn',
                                    'template' => '<div class="btn-group" > {update} {delete} </div>',
                                    'buttons' => [
                                        'delete' => function($url, $model){
                                            return Html::a('<span class="fa fa-trash"></span>', ['deleterole', 'id' => $model->RoleID], [
                                                'class' => 'btn btn-danger click-confirm',
                                                'tittle-alert' => 'Eliminar información',
                                                'text-alert'  => '¿Estás seguro? Cuando elimines el rol, no podrás recuperarlo más tarde.',
                                            ]);
                                        },
                                        'update' => function($url, $model){
                                            return '<button type="button" class="btn btn-color-especial update roleupdate" idrole="'.$model->RoleID.'" data-toggle="modal" data-target="#modal-update"><i class="fa fa-edit"></i></button>';
                                        }
                                       
                                    ],
                                    'contentOptions'=>['style'=>'min-width: 100px; text-align: center; vertical-align:middle;'],
                                ],
                                
                            ],
                            'clientOptions' => [
                            "lengthMenu"=> [[10,20,-1], [10,20,Yii::t('app',"All")]],
                            "info"=>false,
                            "retrieve" => true,
                            "responsive"=>'true', 
                            "dom"=> 'lfTrtip',
                            "tableTools"=>[
                                "aButtons"=> [  
                                ]
                            ],
                            'language'=>[
                                'processing'    => Yii::t('app', 'Procesando...'),
                                'search'        => Yii::t('app', 'Buscar:'),
                                'lengthMenu'    => Yii::t('app','Mostrar _MENU_ Entradas'),
                                'info'        => Yii::t('app','Mostrando del _START_ al _END_ de _TOTAL_ entradas'),
                                'infoEmpty'  => Yii::t('app','Mostrando del 0 al 0 de 0 entradas'),
                                'infoFiltered'  => Yii::t('app','(Filtrado de _MAX_ entradas totales)'),
                                'infoPostFix'   => '',
                                'loadingRecords'=> Yii::t('app','Cargando...'),
                                'zeroRecords'   => Yii::t('app','No se encontraron registros coincidentes'),
                                'emptyTable'    => Yii::t('app','No hay datos disponibles en la tabla'),
                                'paginate' => [
                                    'first'  => Yii::t('app','Primero'),
                                    'previous'  => Yii::t('app','Anterior'),
                                    'next'    => Yii::t('app','Siguiente'),
                                    'last'    => Yii::t('app','Último'),
                                ],
                                'aria' => [
                                    'sortAscending' => Yii::t('app',': activate to sort column ascending'),
                                    'sortDescending'=> Yii::t('app',': activate to sort column descending'),
                                ]
                            ],
                        ],
                    ]);
                ?>
            </div>    
        </div>
    </div>
</div>

<!-- Modal  CREATE-->
<div id="modal-create" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <?php $form = ActiveForm::begin(['action' =>['createrole'], 'id' => 'create-role-modal', 'method' => 'post']); ?>
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 style="color: var(--color-principal);" class="modal-title">Crear rol</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-sm-12">   
                        <?= $form->field($model, 'RoleName')->textInput(['maxlength' => true]); ?>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <?= Html::submitButton('Crear', ['class' => 'btn btn-color-especial click-confirm']) ?>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>

<!-- Modal UPDATE-->
<div id="modal-update" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <?php $form = ActiveForm::begin(['action' =>['updaterole'], 'id' => 'update-role-modal', 'method' => 'post']); ?>
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 style="color: var(--color-principal);" class="modal-title">Actualizar rol</h4>
      </div>
      <div class="modal-body">
        <div class="row">
            <div class="col-sm-12">   
                <?= $form->field($model, 'RoleName')->textInput(['maxlength' => true ,'id'=>'UpdateRole']); ?>
                <?= $form->field($model, 'RoleID')->hiddenInput(['id'=>'UpdateRoleID'])->label(false); ?>
            </div>
        </div>
      </div>
      <div class="modal-footer">
        <?= Html::submitButton('Actualizar', ['class' => 'btn btn-color-especial click-confirm']) ?>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
    <?php ActiveForm::end(); ?>
  </div>
</div>

<?php 
if (Yii::$app->session->hasFlash('success')):
    $this->registerJS('
        $(document).ready(function(){
            _Message("success","¡Exito!","'.Yii::$app->session->getFlash('success').'");
        });

        ');
endif;

if (Yii::$app->session->hasFlash('error')):

    $this->registerJS('
        $(document).ready(function(){
            _Message("error","¡Error!","'.Yii::$app->session->getFlash('error').'");
        });

        ');
endif;

$JS = "
    $(document).on('click','.roleupdate', function(e){
        var idrole = $(this).attr('idrole');
        $.post('ajaxrole',{ id: idrole },function(dt){
            obj = JSON.parse(dt);
            $('#UpdateRoleID').val(obj.RoleID);
            $('#UpdateRole').val(obj.RoleName);
        });
    });
";
$this->registerJS($JS);
?>